"""Publish a collection to the MyACE community collections store.

Exports a user's collection as canonical files and creates a pull request
against the MyACE repository's collections/ directory for admin review.
"""

import uuid

from app.core.config import settings
from app.models.artifact import CanonicalArtifact
from app.services.github_export import (
    GitHubExportError,
    artifacts_to_files,
    parse_repo,
    slugify,
)

# The MyACE community collections repository.
MYACE_COLLECTIONS_REPO = settings.community_repo or "nemmer/MyACE"
MYACE_COLLECTIONS_BASE_BRANCH = "main"


async def publish_collection_to_community(
    *,
    collection_id: uuid.UUID,
    collection_name: str,
    collection_type: str,
    category: str,
    publish_name: str | None,
    publish_description: str | None,
    artifacts: list[CanonicalArtifact],
    github_token: str,
) -> dict:
    """Export a collection's artifacts to the MyACE repo's collections/ folder
    and open a pull request for admin review.

    Returns the PR URL, number, and branch.
    """
    if not artifacts:
        raise GitHubExportError("Nothing to publish — the collection has no artifacts.")

    # Determine the target path in the collections/ folder
    type_dir = "base" if collection_type == "base" else "additional"
    safe_name = slugify(publish_name or collection_name)
    prefix = f"collections/{type_dir}/{safe_name}"

    # Convert artifacts to files, prefixing paths with the collection directory
    files = artifacts_to_files(artifacts)
    prefixed_files: dict[str, str] = {}
    for path, content in files.items():
        prefixed_files[f"{prefix}/{path}"] = content

    # Add a README for the collection
    description = publish_description or f"{collection_name} — a {collection_type} collection"
    readme = f"# {publish_name or collection_name}\n\n{description}\n\n"
    readme += f"**Type:** {collection_type}\n"
    readme += f"**Category:** {category}\n"
    readme += f"**Artifacts:** {len(artifacts)}\n"
    prefixed_files[f"{prefix}/README.md"] = readme

    owner, repo_name = parse_repo(MYACE_COLLECTIONS_REPO)

    new_branch = f"publish-{safe_name}-{uuid.uuid4().hex[:8]}"
    commit_message = f'Publish collection "{publish_name or collection_name}" to community'
    pr_title = f"[Community Collection] {publish_name or collection_name}"
    pr_body = (
        f"## Collection Submission\n\n"
        f"**Name:** {publish_name or collection_name}\n"
        f"**Type:** {collection_type}\n"
        f"**Category:** {category}\n"
        f"**Description:** {publish_description or 'No description provided'}\n"
        f"**Artifacts:** {len(artifacts)}\n\n"
        f"---\n\n"
        f"This PR was automatically generated by MyACE. An admin should review "
        f"the collection contents before merging."
    )

    from app.services.github_export import export_collection_to_github as do_export

    result = await do_export(
        owner=owner,
        repo=repo_name,
        base_branch=MYACE_COLLECTIONS_BASE_BRANCH,
        new_branch=new_branch,
        files=prefixed_files,
        commit_message=commit_message,
        pr_title=pr_title,
        pr_body=pr_body,
        token=github_token,
    )

    result["files_exported"] = len(prefixed_files)
    return result
