import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery, useQueries, useMutation, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowUp, ArrowDown, X, Wrench, Save, Info } from 'lucide-react';
import { collectionsApi, profilesApi } from '../lib/api';
import { useAuth } from '../contexts/AuthContext';
import {
  formatAgentName,
  layoutPipeline,
  PipelineFlowDiagram,
  type PipelineNodeSpec,
  type PipelineEdgeSpec,
} from '../components/PipelineFlow';
import type { Artifact, ArtifactCreate } from '../types';

// ─── Pipeline composition wizard (Epic 3.4) ─────────────────────
//
// V1 is deliberately limited to a single, straight-line sequence — no
// conditional branching (e.g. the software-engineer collection's
// optional security-auditor stage). The generated agent's handoff_to
// lists every stage in order, mirroring how Epic 3.2's hand-written
// orchestrator.md declares its own (branching) chain; someone who wants
// branching can hand-edit the generated agent's handoff_to afterward.

function slugify(value: string): string {
  const slug = value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return slug || 'new-orchestrator';
}

function buildHandoffProse(names: string[]): string {
  if (names.length === 0) return 'No stages selected yet.';
  const formatted = names.map((n) => `\`${n}\``);
  if (formatted.length === 1) return `Delegate to ${formatted[0]}.`;
  const parts = [`Delegate to ${formatted[0]} first.`];
  for (let i = 1; i < formatted.length - 1; i++) {
    parts.push(`Then hand off to ${formatted[i]}.`);
  }
  parts.push(`Finally, hand off to ${formatted[formatted.length - 1]}.`);
  return parts.join(' ');
}

function buildBody(names: string[]): string {
  return [
    'Entry point generated by the pipeline composition wizard. Routes work through a fixed ' +
      'linear sequence of specialist agents — no conditional branching.',
    '',
    '## Handoff',
    '',
    buildHandoffProse(names),
  ].join('\n');
}

export default function OrchestratorBuilder() {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  const [profileId, setProfileId] = useState('');
  const [sequence, setSequence] = useState<string[]>([]);
  const [agentName, setAgentName] = useState('pipeline-orchestrator');
  const [description, setDescription] = useState('');
  const [targetCollectionId, setTargetCollectionId] = useState('');
  const [saveError, setSaveError] = useState<string | null>(null);
  const [savedArtifactName, setSavedArtifactName] = useState<string | null>(null);

  const { data: profiles } = useQuery({
    queryKey: ['profiles'],
    queryFn: () => profilesApi.list(),
  });

  const { data: ownedCollections } = useQuery({
    queryKey: ['collections', { owner_id: user?.id }],
    queryFn: () => collectionsApi.list({ owner_id: user?.id }),
    enabled: !!user,
  });

  const profile = profiles?.find((p) => p.id === profileId) ?? null;
  const resourceCollectionIds = profile
    ? [profile.base_collection_id, ...profile.additional_collection_ids]
    : [];

  const agentQueries = useQueries({
    queries: resourceCollectionIds.map((cid) => ({
      queryKey: ['artifacts', cid, 'agent'],
      queryFn: () => collectionsApi.getArtifacts(cid, { type: 'agent' }),
      enabled: !!profile,
    })),
  });
  const agentsLoading = agentQueries.some((q) => q.isLoading);

  // Combine the way compile_profile() does: later (additional)
  // collections override earlier ones by name.
  const availableAgents = useMemo(() => {
    const byName = new Map<string, Artifact>();
    for (const q of agentQueries) {
      for (const agent of q.data ?? []) {
        byName.set(agent.name, agent);
      }
    }
    return Array.from(byName.values()).sort((a, b) => a.name.localeCompare(b.name));
  }, [agentQueries]);

  const agentsByName = useMemo(
    () => new Map(availableAgents.map((a) => [a.name, a])),
    [availableAgents],
  );

  const addToSequence = (name: string) => {
    setSequence((prev) => (prev.includes(name) ? prev : [...prev, name]));
  };
  const removeFromSequence = (name: string) => {
    setSequence((prev) => prev.filter((n) => n !== name));
  };
  const moveInSequence = (index: number, direction: -1 | 1) => {
    setSequence((prev) => {
      const next = [...prev];
      const target = index + direction;
      if (target < 0 || target >= next.length) return prev;
      [next[index], next[target]] = [next[target], next[index]];
      return next;
    });
  };

  const slug = slugify(agentName);
  const preview = useMemo(() => {
    if (sequence.length === 0) return null;
    const nodeSpecs: PipelineNodeSpec[] = [
      { id: slug, level: 0, label: formatAgentName(slug), isPrimary: true },
      ...sequence.map((name, index) => ({
        id: name,
        level: index + 1,
        label: formatAgentName(name),
        description: agentsByName.get(name)?.description,
      })),
    ];
    const edgeSpecs: PipelineEdgeSpec[] = [];
    const chain = [slug, ...sequence];
    for (let i = 0; i < chain.length - 1; i++) {
      edgeSpecs.push({ id: `${chain[i]}->${chain[i + 1]}`, source: chain[i], target: chain[i + 1] });
    }
    return layoutPipeline(nodeSpecs, edgeSpecs);
  }, [sequence, slug, agentsByName]);

  const createMutation = useMutation({
    mutationFn: (data: ArtifactCreate) => collectionsApi.createArtifact(targetCollectionId, data),
    onSuccess: (created) => {
      queryClient.invalidateQueries({ queryKey: ['artifacts', targetCollectionId] });
      queryClient.invalidateQueries({ queryKey: ['collection', targetCollectionId] });
      setSaveError(null);
      setSavedArtifactName(created.name);
    },
    onError: (err: Error) => setSaveError(err.message),
  });

  const canSave = sequence.length > 0 && !!targetCollectionId && slug.length > 0;

  const handleSave = () => {
    if (!canSave) return;
    setSavedArtifactName(null);
    createMutation.mutate({
      artifact_type: 'agent',
      name: slug,
      priority: 60,
      tags: ['mode:primary'],
      description: description || `Routes work through: ${sequence.join(' -> ')}`,
      body: buildBody(sequence),
      file_path: `agents/${slug}.md`,
      handoff_to: sequence,
    });
  };

  return (
    <div className="space-y-6">
      <Link
        to="/orchestration"
        className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-accent-foreground"
      >
        <ArrowLeft className="h-4 w-4" /> Back to gallery
      </Link>

      <div>
        <h1 className="text-2xl font-bold text-foreground flex items-center gap-2">
          <Wrench className="h-6 w-6 text-muted-foreground" /> Compose Your Pipeline
        </h1>
        <p className="text-muted-foreground mt-1">
          Pick a profile, choose a linear sequence of its agents, and generate a new orchestrator
          agent that routes work through them in order.
        </p>
        <p className="text-sm text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 mt-3 flex items-start gap-2">
          <Info className="h-4 w-4 flex-shrink-0 mt-0.5" />
          <span>
            This wizard only builds a straight-line pipeline. Conditional branching (like the{' '}
            <code className="font-mono text-xs">software-engineer</code> collection's optional
            security-auditor stage) isn't supported here — edit the generated agent's{' '}
            <code className="font-mono text-xs">handoff_to</code> by hand for that.
          </span>
        </p>
      </div>

      <div>
        <label className="block text-sm font-medium text-foreground mb-1">Profile</label>
        <select
          value={profileId}
          onChange={(e) => {
            setProfileId(e.target.value);
            setSequence([]);
          }}
          className="w-full sm:w-96 px-3 py-2 border border-border rounded-lg bg-card text-card-foreground text-sm"
        >
          <option value="">Select a profile...</option>
          {(profiles ?? []).map((p) => (
            <option key={p.id} value={p.id}>
              {p.name}
            </option>
          ))}
        </select>
      </div>

      {profile && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="bg-card border border-border rounded-xl p-4">
            <h2 className="text-sm font-semibold text-card-foreground mb-3">Available agents</h2>
            {agentsLoading ? (
              <p className="text-sm text-muted-foreground">Loading agents...</p>
            ) : availableAgents.length === 0 ? (
              <p className="text-sm text-muted-foreground">This profile has no agent artifacts.</p>
            ) : (
              <ul className="space-y-2">
                {availableAgents.map((agent) => (
                  <li key={agent.name} className="flex items-center justify-between gap-2">
                    <div className="min-w-0">
                      <div className="text-sm font-medium text-card-foreground truncate">
                        {formatAgentName(agent.name)}
                      </div>
                      {agent.description && (
                        <div className="text-xs text-muted-foreground truncate">{agent.description}</div>
                      )}
                    </div>
                    <button
                      onClick={() => addToSequence(agent.name)}
                      disabled={sequence.includes(agent.name)}
                      className="text-xs font-medium px-2 py-1 rounded-md border border-border text-muted-foreground hover:text-accent-foreground hover:bg-accent disabled:opacity-40 disabled:cursor-not-allowed flex-shrink-0"
                    >
                      {sequence.includes(agent.name) ? 'Added' : 'Add'}
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </div>

          <div className="bg-card border border-border rounded-xl p-4">
            <h2 className="text-sm font-semibold text-card-foreground mb-3">Pipeline sequence</h2>
            {sequence.length === 0 ? (
              <p className="text-sm text-muted-foreground">Add agents from the left to build a sequence.</p>
            ) : (
              <ol className="space-y-2">
                {sequence.map((name, index) => (
                  <li
                    key={name}
                    className="flex items-center justify-between gap-2 bg-muted/40 rounded-lg px-3 py-2"
                  >
                    <span className="text-sm text-card-foreground">
                      <span className="text-muted-foreground mr-1.5">{index + 1}.</span>
                      {formatAgentName(name)}
                    </span>
                    <div className="flex items-center gap-1 flex-shrink-0">
                      <button
                        onClick={() => moveInSequence(index, -1)}
                        disabled={index === 0}
                        className="p-1 text-muted-foreground hover:text-accent-foreground disabled:opacity-30"
                        aria-label="Move up"
                      >
                        <ArrowUp className="h-3.5 w-3.5" />
                      </button>
                      <button
                        onClick={() => moveInSequence(index, 1)}
                        disabled={index === sequence.length - 1}
                        className="p-1 text-muted-foreground hover:text-accent-foreground disabled:opacity-30"
                        aria-label="Move down"
                      >
                        <ArrowDown className="h-3.5 w-3.5" />
                      </button>
                      <button
                        onClick={() => removeFromSequence(name)}
                        className="p-1 text-muted-foreground hover:text-destructive"
                        aria-label="Remove"
                      >
                        <X className="h-3.5 w-3.5" />
                      </button>
                    </div>
                  </li>
                ))}
              </ol>
            )}
          </div>
        </div>
      )}

      {preview && (
        <div>
          <h2 className="text-sm font-semibold text-card-foreground mb-3">Preview</h2>
          <PipelineFlowDiagram nodes={preview.nodes} edges={preview.edges} />
        </div>
      )}

      {sequence.length > 0 && (
        <div className="bg-card border border-border rounded-xl p-5 space-y-4">
          <h2 className="text-sm font-semibold text-card-foreground">Generate &amp; save</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-medium text-muted-foreground mb-1">Agent name</label>
              <input
                value={agentName}
                onChange={(e) => setAgentName(e.target.value)}
                className="w-full px-3 py-2 border border-border rounded-lg bg-background text-foreground text-sm"
              />
              <p className="text-xs text-muted-foreground mt-1">
                Saved as <code className="font-mono">{slug}</code>
              </p>
            </div>
            <div>
              <label className="block text-xs font-medium text-muted-foreground mb-1">
                Save into collection
              </label>
              <select
                value={targetCollectionId}
                onChange={(e) => setTargetCollectionId(e.target.value)}
                className="w-full px-3 py-2 border border-border rounded-lg bg-background text-foreground text-sm"
              >
                <option value="">Select one of your collections...</option>
                {(ownedCollections ?? []).map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.name}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <div>
            <label className="block text-xs font-medium text-muted-foreground mb-1">
              Description (optional)
            </label>
            <input
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder={`Routes work through: ${sequence.join(' -> ')}`}
              className="w-full px-3 py-2 border border-border rounded-lg bg-background text-foreground text-sm"
            />
          </div>

          {saveError && <p className="text-sm text-destructive">{saveError}</p>}
          {savedArtifactName && !createMutation.isPending && (
            <p className="text-sm text-green-700">
              Saved <code className="font-mono">{savedArtifactName}</code>. View it in the{' '}
              <Link to="/orchestration" className="underline">
                Orchestration Gallery
              </Link>
              .
            </p>
          )}

          <button
            onClick={handleSave}
            disabled={!canSave || createMutation.isPending}
            className="inline-flex items-center gap-1.5 px-4 py-2 bg-brand-600 text-white text-sm font-medium rounded-lg hover:bg-brand-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Save className="h-4 w-4" /> {createMutation.isPending ? 'Saving...' : 'Generate & save'}
          </button>
        </div>
      )}
    </div>
  );
}
